"""
Build Agent for Lexstudio
Task-oriented agent for Build Mode with 10-step unified workflow.
Uses openai client directly for compatibility with third-party API providers.
"""

from openai import AsyncOpenAI, OpenAI, APITimeoutError, APIConnectionError
from dotenv import load_dotenv
from typing import AsyncIterator, Dict, Any
import os
import asyncio

load_dotenv()

# Configure timeout settings
REQUEST_TIMEOUT = 90.0  # 90 seconds timeout for build mode (longer responses)
CONNECT_TIMEOUT = 15.0  # 15 seconds to establish connection

_async_client = AsyncOpenAI(
    api_key=os.getenv("OPENAI_API_KEY"),
    base_url=os.getenv("OPENAI_BASE_URL"),
    timeout=REQUEST_TIMEOUT,
)

_sync_client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY"),
    base_url=os.getenv("OPENAI_BASE_URL"),
    timeout=REQUEST_TIMEOUT,
)

# Keep llm for generate_step_content / generate_project_title (sync invoke)
from langchain_openai import ChatOpenAI
llm = ChatOpenAI(
    model=os.getenv("MODEL_NAME"),
    temperature=0.7,
    api_key=os.getenv("OPENAI_API_KEY"),
    base_url=os.getenv("OPENAI_BASE_URL"),
    request_timeout=REQUEST_TIMEOUT,
)

MODEL = os.getenv("MODEL_NAME", "gpt-4o")

# Unified 10-step workflow (replaces WHITEPAPER_STEPS + CONTRACT_STEPS)
UNIFIED_STEPS = {
    0: "Asset Identity — Asset name, token symbol, category, description",
    1: "Issuer & Legal — Issuer entity, registration, team, governance",
    2: "Token Economics — Total supply, allocation, vesting schedule",
    3: "Legal & Compliance — Offering route, KYC provider, investor qualifications",
    4: "Valuation & Yield — Asset valuation, yield rate, Oracle preference",
    5: "Token Classification — Legal classification, holder rights, ERC-3643 config",
    6: "Transfer & Minting — Whitelist mode, minting permissions, transfer restrictions",
    7: "Technology — Deploy network, audit firm, multisig config",
    8: "Market & Risks — Exchange plans, risk matrix, incident response",
    9: "Final Review — Signatories, test plan confirmation, final assembly",
}

# ERC-3643 T-REX initial template (returned by /api/build/templates)
ERC3643_TEMPLATE = """// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.20;

// ERC-3643 T-REX RWA Token — Generated by Lexstudio
// Replace /* PLACEHOLDER */ comments before deployment

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/security/Pausable.sol";

contract /* TOKEN_NAME */ is Ownable, Pausable {
    string public name = "/* TOKEN_FULL_NAME */";
    string public symbol = "/* TOKEN_SYMBOL */";
    uint8 public decimals = 18;
    uint256 public totalSupply = /* TOTAL_SUPPLY */;

    address public identityRegistry;  // /* IDENTITY_REGISTRY_ADDRESS */
    address public compliance;        // /* COMPLIANCE_MODULE_ADDRESS */

    mapping(address => uint256) private _balances;
    mapping(address => bool) public frozen;

    event Transfer(address indexed from, address indexed to, uint256 value);
    event TokensFrozen(address indexed wallet);
    event TokensUnfrozen(address indexed wallet);

    modifier onlyVerifiedInvestor(address _to) {
        // Identity check via IIdentityRegistry
        _;
    }

    function transfer(address to, uint256 amount)
        public whenNotPaused onlyVerifiedInvestor(to) returns (bool) {
        // Compliance check before transfer
        _transfer(msg.sender, to, amount);
        return true;
    }

    function mint(address to, uint256 amount) external onlyOwner {
        // /* MINTING_AUTHORITY_CHECK */
        _balances[to] += amount;
        totalSupply += amount;
        emit Transfer(address(0), to, amount);
    }

    function freeze(address wallet) external onlyOwner {
        frozen[wallet] = true;
        emit TokensFrozen(wallet);
    }

    function _transfer(address from, address to, uint256 amount) internal {
        require(!frozen[from], "Sender frozen");
        require(!frozen[to], "Recipient frozen");
        require(_balances[from] >= amount, "Insufficient balance");
        _balances[from] -= amount;
        _balances[to] += amount;
        emit Transfer(from, to, amount);
    }
}"""

# Default Mermaid arch map template
ARCH_MAP_TEMPLATE = """graph TD
  Investor([Investor]) -->|KYC/AML| IR[Identity Registry]
  IR -->|Verified| Token["ERC-3643 Token\\n/* TOKEN_SYMBOL */"]
  Token -->|Transfer Check| CM[Compliance Module]
  CM -->|/* JURISDICTION */ Rules| JR[(Rule Engine)]
  Token -->|NAV Feed| Oracle[Price Oracle]
  Issuer([/* ISSUER_NAME */]) -->|Mint/Burn| Token
  Token -->|Yield| Investor"""

# Step-specific content generation prompts (returns JSON with wp + contract + arch_map)
STEP_CONTENT_PROMPTS = {
    0: """Based on the conversation, generate structured content for Step 0: Asset Identity.
Return a JSON object with EXACTLY these three keys:

{
  "whitepaper_content": "## Executive Summary\\n\\n- **Project Name**: [name]\\n- **Token Symbol**: [symbol]\\n- **Asset Category**: [category]\\n- **Brief Description**: [1-2 sentences]\\n\\nOnly include information actually provided. Use TBD for missing.",
  "contract_snippet": "    string public name = \\"[TOKEN_FULL_NAME]\\";\\n    string public symbol = \\"[TOKEN_SYMBOL]\\";\\n    uint8 public decimals = 18;",
  "arch_map_update": "graph TD\\n  Investor([Investor]) -->|KYC/AML| IR[Identity Registry]\\n  IR -->|Verified| Token[\\"ERC-3643 Token\\\\n[TOKEN_SYMBOL]\\"]\\n  Token -->|Transfer Check| CM[Compliance Module]\\n  CM -->|Rules| JR[(Rule Engine)]\\n  Token -->|NAV Feed| Oracle[Price Oracle]\\n  Issuer([Issuer]) -->|Mint/Burn| Token\\n  Token -->|Yield| Investor"
}

Replace placeholders with actual values from the conversation. Return ONLY valid JSON.""",

    1: """Based on the conversation, generate structured content for Step 1: Issuer & Legal.
Return a JSON object:

{
  "whitepaper_content": "## Issuer & Governance\\n\\n### Issuer Information\\n- **Legal Entity Name**: [name]\\n- **Registration Jurisdiction**: [jurisdiction]\\n- **Registration Number**: [number or TBD]\\n\\n### Governance Structure\\n[Describe decision-making structure if discussed]",
  "contract_snippet": "    // IdentityRegistry admin roles\\n    address public issuerAdmin = /* ISSUER_ADMIN_ADDRESS */;\\n    address public complianceOfficer = /* COMPLIANCE_OFFICER_ADDRESS */;",
  "arch_map_update": ""
}

Return ONLY valid JSON. Empty string for arch_map_update if no changes needed.""",

    2: """Based on the conversation, generate structured content for Step 2: Token Economics.
Return a JSON object:

{
  "whitepaper_content": "## Tokenomics\\n\\n### Token Supply\\n- **Total Supply**: [amount]\\n- **Initial Circulating Supply**: [amount or TBD]\\n\\n### Allocation\\n[Distribution breakdown: Team / Investors / Treasury / Public]\\n\\n### Unlock Schedule\\n[Vesting or lock-up periods]",
  "contract_snippet": "    uint256 public totalSupply = /* TOTAL_SUPPLY */;\\n    uint256 public maxBalance = /* MAX_BALANCE_PER_HOLDER */; // Optional cap",
  "arch_map_update": ""
}

Return ONLY valid JSON.""",

    3: """Based on the conversation, generate structured content for Step 3: Legal & Compliance.
Return a JSON object:

{
  "whitepaper_content": "## Legal & Regulatory\\n\\n### Offering Structure\\n- **Offering Route**: [route]\\n- **Jurisdictions**: [countries]\\n- **Eligible Investors**: [type]\\n\\n### KYC/AML Compliance\\n- **KYC Provider**: [provider]\\n- **AML Policy**: [description]",
  "contract_snippet": "    // ICompliance interface\\n    interface ICompliance {\\n        function canTransfer(address from, address to, uint256 amount) external view returns (bool);\\n    }\\n    ICompliance public compliance; // /* COMPLIANCE_MODULE_ADDRESS */",
  "arch_map_update": ""
}

Return ONLY valid JSON.""",

    4: """Based on the conversation, generate structured content for Step 4: Valuation & Yield.
Return a JSON object:

{
  "whitepaper_content": "## Valuation & Fundraising\\n\\n### Asset Valuation\\n- **Current NAV**: [valuation]\\n- **Annual Yield Rate**: [rate]%\\n\\n### Oracle Configuration\\n- **Oracle Provider**: [provider or TBD]\\n- **Update Frequency**: [frequency]",
  "contract_snippet": "    // IOracle integration\\n    interface IOracle {\\n        function getAssetValue() external view returns (uint256);\\n    }\\n    IOracle public valuationOracle; // /* ORACLE_ADDRESS */\\n\\n    function distributeYield() external onlyOwner {\\n        // Yield distribution logic\\n    }",
  "arch_map_update": ""
}

Return ONLY valid JSON.""",

    5: """Based on the conversation, generate structured content for Step 5: Token Classification.
Return a JSON object:

{
  "whitepaper_content": "## Token Overview & Classification\\n\\n### Legal Classification\\n- **Classification**: [Security Token / Utility Token / Payment Token]\\n- **Applicable Standard**: [regulatory framework]\\n- **Transferability**: [Restricted / Unrestricted]\\n\\n### Token Rights\\n[Holder rights: voting, dividends, redemption]",
  "contract_snippet": "    // ERC-3643 T-REX base — Token Classification\\n    // Classification: /* TOKEN_CLASSIFICATION */\\n    // Standard: ERC-3643\\n    // Transferability: Restricted (whitelist required)",
  "arch_map_update": ""
}

Return ONLY valid JSON.""",

    6: """Based on the conversation, generate structured content for Step 6: Transfer & Minting.
Return a JSON object:

{
  "whitepaper_content": "## Transfer Restrictions\\n\\n### Whitelist Requirements\\n- **Whitelist Mode**: [enabled/disabled]\\n- **Minting Authority**: [who can mint]\\n\\n### Transfer Rules\\n- **Transfer Restrictions**: [description]\\n- **Burn Conditions**: [conditions]",
  "contract_snippet": "    function transfer(address to, uint256 amount)\\n        public whenNotPaused onlyVerifiedInvestor(to) returns (bool) {\\n        _transfer(msg.sender, to, amount);\\n        return true;\\n    }\\n\\n    function mint(address to, uint256 amount) external onlyOwner {\\n        _balances[to] += amount;\\n        totalSupply += amount;\\n        emit Transfer(address(0), to, amount);\\n    }\\n\\n    function burn(address from, uint256 amount) external onlyOwner {\\n        require(_balances[from] >= amount, \\"Insufficient balance\\");\\n        _balances[from] -= amount;\\n        totalSupply -= amount;\\n        emit Transfer(from, address(0), amount);\\n    }",
  "arch_map_update": ""
}

Return ONLY valid JSON.""",

    7: """Based on the conversation, generate structured content for Step 7: Technology.
Return a JSON object:

{
  "whitepaper_content": "## Technology & Security\\n\\n### Blockchain Infrastructure\\n- **Deploy Network**: [network]\\n- **Token Standard**: ERC-3643\\n\\n### Security\\n- **Audit Firm**: [firm or TBD]\\n- **Multisig Config**: [config]\\n- **Upgrade Strategy**: [strategy]",
  "contract_snippet": "    // AccessControl + Pausable\\n    // Deploy Network: /* DEPLOY_NETWORK */\\n    // Audit: /* AUDIT_FIRM */\\n\\n    function pause() external onlyOwner {\\n        _pause();\\n    }\\n\\n    function unpause() external onlyOwner {\\n        _unpause();\\n    }",
  "arch_map_update": ""
}

Return ONLY valid JSON.""",

    8: """Based on the conversation, generate structured content for Step 8: Market & Risks.
Return a JSON object:

{
  "whitepaper_content": "## Listing & Market\\n\\n### Exchange Plans\\n[Planned exchange listings and trading pairs]\\n\\n## Key Risks\\n\\n### Risk Matrix\\n[Legal, technical, market, operational risks]\\n\\n## Incident Response\\n\\n### Emergency Procedures\\n- **Emergency Pause**: Supported via Pausable\\n- **Incident Communication**: [plan]",
  "contract_snippet": "    // Emergency controls\\n    function pause() external onlyOwner { _pause(); }\\n    function unpause() external onlyOwner { _unpause(); }\\n    function freeze(address wallet) external onlyOwner {\\n        frozen[wallet] = true;\\n        emit TokensFrozen(wallet);\\n    }",
  "arch_map_update": ""
}

Return ONLY valid JSON.""",

    9: """Based on the conversation, generate the Final Review — complete whitepaper assembly and finalized contract.
Return a JSON object:

{
  "whitepaper_content": "## Declarations & Signatures\\n\\n### Authenticity Statement\\nThe information contained in this whitepaper is accurate and complete to the best of the issuer's knowledge.\\n\\n### Risk Disclosure\\nInvestment in tokenized assets involves risk. Past performance is not indicative of future results.\\n\\n### Regulatory Disclaimer\\nThis document does not constitute financial advice. Consult qualified professionals before investing.\\n\\n### Signatories\\n[Authorized representative names, titles, date]\\n\\n---\\n*Generated by Lexstudio — Chainlex.ai*",
  "contract_snippet": "// Final Review Complete\\n// All parameters confirmed. Ready for audit and deployment.\\n// Audit Firm: /* AUDIT_FIRM */\\n// Deploy Network: /* DEPLOY_NETWORK */",
  "arch_map_update": ""
}

Return ONLY valid JSON.""",
}

TITLE_GENERATION_PROMPT = """Based on the conversation, generate a concise, professional title for this RWA tokenization project.

Rules:
1. Maximum 30 characters in Chinese or 40 characters in English
2. Format: [Asset Name] + [RWA/代币化] if applicable
3. Examples: "银河大厦RWA", "上海浦东写字楼代币化", "Manhattan Office RWA"
4. If not enough information, return "待命名项目"

Return ONLY the title, nothing else."""


def generate_step_content(
    step: int,
    phase: str,
    history: list,
    asset_data: Dict[str, Any]
) -> Dict[str, str]:
    """Generate structured content for a completed step. Returns dict with wp, contract, arch_map."""
    try:
        if step not in STEP_CONTENT_PROMPTS:
            return {"whitepaper_content": "", "contract_snippet": "", "arch_map_update": ""}

        content_prompt = STEP_CONTENT_PROMPTS[step]

        summary_prompt = f"""
You are a professional RWA documentation assistant.

{content_prompt}

Conversation history to extract information from:
{chr(10).join([f"{m.get('role', 'user')}: {m.get('content', '')}" for m in history[-10:]])}

Current asset data: {asset_data}

Generate the structured content now. Return ONLY valid JSON with keys: whitepaper_content, contract_snippet, arch_map_update.
"""

        response = llm.invoke(summary_prompt)
        raw = response.content if hasattr(response, 'content') else str(response)

        # Parse JSON response
        import json
        import re
        # Extract JSON block if wrapped in markdown
        json_match = re.search(r'\{.*\}', raw, re.DOTALL)
        if json_match:
            result = json.loads(json_match.group())
            return {
                "whitepaper_content": result.get("whitepaper_content", ""),
                "contract_snippet": result.get("contract_snippet", ""),
                "arch_map_update": result.get("arch_map_update", ""),
            }
        return {"whitepaper_content": raw, "contract_snippet": "", "arch_map_update": ""}

    except Exception as e:
        return {"whitepaper_content": f"Content generation error: {str(e)}", "contract_snippet": "", "arch_map_update": ""}


def generate_project_title(
    history: list,
    asset_data: Dict[str, Any]
) -> str:
    """Generate a professional project title"""
    try:
        summary_prompt = f"""
{TITLE_GENERATION_PROMPT}

Conversation history:
{chr(10).join([f"{m.get('role', 'user')}: {m.get('content', '')}" for m in history[-6:]])}

Current asset data: {asset_data}

Generate the title now. Return ONLY the title.
"""

        response = llm.invoke(summary_prompt)
        title = response.content if hasattr(response, 'content') else str(response)
        title = title.strip().strip('"\'')
        if len(title) > 40:
            title = title[:37] + "..."
        return title

    except Exception as e:
        return "待命名项目"


def get_system_prompt(phase: str, current_step: int, completed_steps: list, asset_data: Dict[str, Any] = None) -> str:
    """Generate system prompt based on current step in unified workflow"""

    current_step_name = UNIFIED_STEPS.get(current_step, "Unknown Step")
    total_steps = len(UNIFIED_STEPS)

    base_prompt = (
        f"You are Lexstudio Build Mode AI. Guide users through RWA asset tokenization.\n\n"
        f"**Current**: Step {current_step + 1}/{total_steps} - {current_step_name}\n\n"
        "## CRITICAL: Language Rule\n"
        "Always respond in the SAME language the user writes in. If they write English, reply in English. "
        "If they write Chinese, reply in Chinese. Never mix languages in a single response. "
        "All generated whitepaper/contract document content must be in professional English regardless of conversation language.\n\n"
        "## Response Rules\n"
        "- Keep replies concise (2-4 sentences max)\n"
        "- Ask only 1-2 focused questions at a time\n"
        "- No greetings or filler words\n"
        "- When the user provides information, briefly acknowledge what was captured, then ask the next question\n"
        "- When all required info for this step is collected, summarize and tell the user they can move on\n"
        "- Never just say a single word or phrase like 'confirmed' with no follow-up guidance\n\n"
        "## Step Focus\n"
    )

    step_focus = {
        0: "Collect: asset name, token symbol (e.g. RWA-XXX), asset category (Real Estate/Bond/Equity/Fund), brief description",
        1: "Collect: issuer legal entity name, registration jurisdiction, core team roles, governance structure",
        2: "Collect: total token supply, allocation breakdown (team/investors/treasury/public), vesting/lock-up schedule",
        3: "Collect: offering route (private placement/Reg D/etc.), target investor type (accredited/institutional), KYC/AML provider",
        4: "Collect: current asset valuation, expected annual yield rate (%), Oracle provider preference (Chainlink/custom/TBD)",
        5: "Collect: legal token classification (security/utility/payment token), applicable regulatory standard, holder rights (voting/dividends/redemption)",
        6: "Collect: whitelist requirement (yes/no), who has minting authority, any transfer restrictions or lock-up periods",
        7: "Collect: target deploy network (Ethereum/Polygon/etc.), audit firm (if any), multisig wallet config, upgrade strategy (proxy/immutable)",
        8: "Collect: exchange listing plans, key risk factors (legal/technical/market/operational), incident response plan",
        9: "Confirm all information is complete and accurate; collect authorized signatories; finalize risk disclaimers and test plan",
    }
    base_prompt += step_focus.get(current_step, "Collect required information for this step.")

    # Inject jurisdiction context
    if asset_data and asset_data.get('jurisdictions'):
        jurisdiction_names = {
            'HK': 'Hong Kong (SFC/HKMA framework)',
            'UAE': 'UAE (ADGM/VARA framework)',
            'US': 'United States (SEC/FINRA framework)',
            'SG': 'Singapore (MAS framework)',
        }
        j_list = ', '.join([jurisdiction_names.get(j, j) for j in asset_data['jurisdictions']])
        base_prompt += f"\n\n## Regulatory Context\nThis token is being issued under: {j_list}\nAll compliance guidance must align with these jurisdictions."

    # Inject uploaded file summaries
    if asset_data and asset_data.get('uploadedFiles'):
        base_prompt += "\n\n## Uploaded Materials\n"
        for f in asset_data['uploadedFiles'][:3]:
            base_prompt += f"- {f['name']}: {f.get('content', '')[:500]}\n"

    return base_prompt


def _build_messages(user_input: str, history: list, system_prompt: str) -> list:
    """Convert history + user input into OpenAI message dicts."""
    messages = [{"role": "system", "content": system_prompt}]
    for msg in history:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        if role in ("user", "assistant"):
            messages.append({"role": role, "content": content})
    messages.append({"role": "user", "content": user_input})
    return messages


async def stream_build_agent(
    user_input: str,
    history: list,
    current_step: int,
    completed_steps: list,
    phase: str,
    asset_data: Dict[str, Any]
) -> AsyncIterator[str]:
    """Stream the build agent response token by token with timeout handling."""
    try:
        system_prompt = get_system_prompt(phase, current_step, completed_steps, asset_data)
        messages = _build_messages(user_input, history, system_prompt)

        # Create stream with timeout
        stream = await asyncio.wait_for(
            _async_client.chat.completions.create(
                model=MODEL,
                messages=messages,
                stream=True,
            ),
            timeout=CONNECT_TIMEOUT
        )

        async for chunk in stream:
            delta = chunk.choices[0].delta.content if chunk.choices else None
            if delta:
                yield delta

    except asyncio.TimeoutError:
        yield "\n\n⚠️ Connection timeout. The AI service is taking too long to respond. Please try again."
    except APITimeoutError:
        yield "\n\n⚠️ API timeout. Please check your network connection and try again."
    except APIConnectionError as e:
        yield f"\n\n⚠️ Connection error: {str(e)}. Please check if the API endpoint is accessible."
    except Exception as e:
        yield f"\n\n⚠️ Error: {str(e)}"


def run_build_agent(
    user_input: str,
    history: list,
    current_step: int,
    completed_steps: list,
    phase: str,
    asset_data: Dict[str, Any]
) -> str:
    """Run the build agent (non-streaming fallback)."""
    try:
        system_prompt = get_system_prompt(phase, current_step, completed_steps, asset_data)
        messages = _build_messages(user_input, history, system_prompt)
        response = _sync_client.chat.completions.create(
            model=MODEL,
            messages=messages,
            stream=False,
        )
        return response.choices[0].message.content or ""
    except Exception as e:
        return f"I encountered an error: {str(e)}. Please try again."
